CREATE TABLE dbo.users
(
	userID INT PRIMARY KEY IDENTITY (1, 1),
	fullname VARCHAR(500) NOT NULL,
	email VARCHAR(255) NOT NULL,
	pwd VARCHAR(255) NOT NULL,
	dateCreation SMALLDATETIME NOT NULL DEFAULT GETDATE()
)